### ISSUE TITLE
The sequence of the pairs are different for uniSwap and other DEX

### ISSUE THREAD

**Issue by ruiyangthu** [hmprt/arbitrageTrackerV1#3]
the sequence of the pairs are different for uniSwap and other DEX, as a result, the sequence of Pool_1 and Pool_0 returned is not what we expected. This is the reason why sometimes the liquidity is zero and we get the wrong price from UniSwap.  For example. We expect pool_0 for USDT (decimals 6) pool_1 for DAI (decimals 18), but, if pool_1 returned is for USDT, when pool_USDT/1**10^18 we get a near-Zero number. 

 But, what we should pay more attention are the pairs with the same decimals, the result sounds good, but the price may be wrong!  which is very dangerous as a reference for arbitrage operation.   

Again, Thanks for your contribution, and hopefully V2 is coming soon .....

**Comment by hmprt** [comment]
Hey, thanks for the detailed writeup!

This was my first pass at arbitrage logic - I also identified this issue, but it took a long time - I wish I had seen your response first!
This is ideally fixed in Version 2!

My current fix is to have different pricing methods for every exchange - not ideal, but these things need to be done. I am also rewriting tradingPairs as a fully bidirectional class which can swap token1/0 very easily - this should make it easier to work with different exchanges which order pairs differently. 

Thanks for taking the time to read and implement my code!

~hmprt
